# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QThread, pyqtSignal
from PyQt5.QtWidgets import *
from functools import partial
import sys, os
import subprocess
import json
import queue
import threading
import time


class Worker(QThread):
    result_signal = pyqtSignal(str)
    finished = pyqtSignal()
    def __init__(self, ssh_cmd, cmd):
        super().__init__()
        self.ssh_cmd = ssh_cmd
        self.cmd = cmd
    def run(self):
        try:
            process = subprocess.Popen(self.ssh_cmd + self.cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

            def enqueue_output(pipe, q):
                for line in iter(pipe.readline, b''):
                    q.put(line.decode('utf-8', errors='ignore'))
                pipe.close()

            stdout_queue = queue.Queue()
            stderr_queue = queue.Queue()

            stdout_thread = threading.Thread(target=enqueue_output, args=(process.stdout, stdout_queue))
            stderr_thread = threading.Thread(target=enqueue_output, args=(process.stderr, stderr_queue))

            stdout_thread.start()
            stderr_thread.start()

            while stdout_thread.is_alive() or stderr_thread.is_alive():
                try:
                    stdout_line = stdout_queue.get_nowait()
                except queue.Empty:
                    stdout_line = None
                if stdout_line:
                    self.result_signal.emit(stdout_line.strip())

                try:
                    stderr_line = stderr_queue.get_nowait()
                except queue.Empty:
                    stderr_line = None
                if stderr_line:
                    self.result_signal.emit(stderr_line.strip())

            while not stdout_queue.empty():
                self.result_signal.emit(stdout_queue.get().strip())
            while not stderr_queue.empty():
                self.result_signal.emit(stderr_queue.get().strip())

            stdout_thread.join()
            stderr_thread.join()

        except Exception as e:
            self.result_signal.emit(str(e))
        finally:
            self.finished.emit()
            self.quit()


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(811, 597)
        
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 791, 571))
        self.tabWidget.setObjectName("tabWidget")
        
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(20, 10, 751, 511))
        self.tabWidget_2.setObjectName("tabWidget_2")
        
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        
        self.label = QtWidgets.QLabel(self.tab_5)
        self.label.setGeometry(QtCore.QRect(60, 30, 67, 17))
        self.label.setObjectName("label")
        
        self.label_2 = QtWidgets.QLabel(self.tab_5)
        self.label_2.setGeometry(QtCore.QRect(50, 70, 81, 20))
        self.label_2.setObjectName("label_2")
        
        self.label_3 = QtWidgets.QLabel(self.tab_5)
        self.label_3.setGeometry(QtCore.QRect(70, 110, 51, 20))
        self.label_3.setObjectName("label_3")
        
        self.label_4 = QtWidgets.QLabel(self.tab_5)
        self.label_4.setGeometry(QtCore.QRect(80, 150, 41, 20))
        self.label_4.setObjectName("label_4")
        
        self.lineEdit = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit.setGeometry(QtCore.QRect(160, 30, 451, 25))
        self.lineEdit.setObjectName("lineEdit")
        
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 70, 451, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_3.setGeometry(QtCore.QRect(160, 110, 451, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_4.setGeometry(QtCore.QRect(160, 150, 451, 25))
        self.lineEdit_4.setObjectName("lineEdit_4")
        
        self.toolButton = QtWidgets.QToolButton(self.tab_5)
        self.toolButton.setGeometry(QtCore.QRect(640, 30, 26, 24))
        self.toolButton.setObjectName("toolButton")
        
        self.pushButton = QtWidgets.QPushButton(self.tab_5)
        self.pushButton.setGeometry(QtCore.QRect(330, 190, 89, 25))
        self.pushButton.setObjectName("pushButton")
        
        self.textEdit = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit.setGeometry(QtCore.QRect(30, 230, 691, 231))
        self.textEdit.setObjectName("textEdit")
        
        self.tabWidget_2.addTab(self.tab_5, "")
        
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_5.setGeometry(QtCore.QRect(160, 30, 451, 25))
        self.lineEdit_5.setObjectName("lineEdit_5")
        
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_6)
        self.textEdit_2.setGeometry(QtCore.QRect(30, 230, 691, 231))
        self.textEdit_2.setObjectName("textEdit_2")
        
        self.label_5 = QtWidgets.QLabel(self.tab_6)
        self.label_5.setGeometry(QtCore.QRect(50, 70, 81, 20))
        self.label_5.setObjectName("label_5")
        
        self.label_6 = QtWidgets.QLabel(self.tab_6)
        self.label_6.setGeometry(QtCore.QRect(70, 110, 51, 20))
        self.label_6.setObjectName("label_6")
        
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_6.setGeometry(QtCore.QRect(160, 70, 451, 25))
        self.lineEdit_6.setObjectName("lineEdit_6")
        
        self.toolButton_2 = QtWidgets.QToolButton(self.tab_6)
        self.toolButton_2.setGeometry(QtCore.QRect(640, 30, 26, 24))
        self.toolButton_2.setObjectName("toolButton_2")
        
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_7.setGeometry(QtCore.QRect(160, 150, 451, 25))
        self.lineEdit_7.setObjectName("lineEdit_7")
        
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_8.setGeometry(QtCore.QRect(160, 110, 451, 25))
        self.lineEdit_8.setObjectName("lineEdit_8")
        
        self.label_7 = QtWidgets.QLabel(self.tab_6)
        self.label_7.setGeometry(QtCore.QRect(60, 30, 67, 17))
        self.label_7.setObjectName("label_7")
        
        self.label_8 = QtWidgets.QLabel(self.tab_6)
        self.label_8.setGeometry(QtCore.QRect(80, 150, 41, 20))
        self.label_8.setObjectName("label_8")
        
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 190, 89, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        
        self.tabWidget_2.addTab(self.tab_6, "")
        
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_9.setGeometry(QtCore.QRect(160, 30, 451, 25))
        self.lineEdit_9.setObjectName("lineEdit_9")
        
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab_7)
        self.textEdit_3.setGeometry(QtCore.QRect(30, 230, 691, 231))
        self.textEdit_3.setObjectName("textEdit_3")
        
        self.label_9 = QtWidgets.QLabel(self.tab_7)
        self.label_9.setGeometry(QtCore.QRect(50, 70, 81, 20))
        self.label_9.setObjectName("label_9")
        
        self.label_10 = QtWidgets.QLabel(self.tab_7)
        self.label_10.setGeometry(QtCore.QRect(70, 110, 51, 20))
        self.label_10.setObjectName("label_10")
        
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_10.setGeometry(QtCore.QRect(160, 70, 451, 25))
        self.lineEdit_10.setObjectName("lineEdit_10")
        
        self.toolButton_3 = QtWidgets.QToolButton(self.tab_7)
        self.toolButton_3.setGeometry(QtCore.QRect(640, 30, 26, 24))
        self.toolButton_3.setObjectName("toolButton_3")
        
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_11.setGeometry(QtCore.QRect(160, 150, 451, 25))
        self.lineEdit_11.setObjectName("lineEdit_11")
        
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_12.setGeometry(QtCore.QRect(160, 110, 451, 25))
        self.lineEdit_12.setObjectName("lineEdit_12")
        
        self.label_11 = QtWidgets.QLabel(self.tab_7)
        self.label_11.setGeometry(QtCore.QRect(60, 30, 67, 17))
        self.label_11.setObjectName("label_11")
        
        self.label_12 = QtWidgets.QLabel(self.tab_7)
        self.label_12.setGeometry(QtCore.QRect(80, 150, 41, 20))
        self.label_12.setObjectName("label_12")
        
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_3.setGeometry(QtCore.QRect(330, 190, 89, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        
        self.tabWidget_2.addTab(self.tab_7, "")
        
        self.tabWidget.addTab(self.tab, "")
        
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_3.setGeometry(QtCore.QRect(20, 10, 751, 511))
        self.tabWidget_3.setObjectName("tabWidget_3")
        
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        
        self.label_25 = QtWidgets.QLabel(self.tab_11)
        self.label_25.setGeometry(QtCore.QRect(60, 30, 67, 17))
        self.label_25.setObjectName("label_25")
        
        self.label_26 = QtWidgets.QLabel(self.tab_11)
        self.label_26.setGeometry(QtCore.QRect(50, 70, 81, 20))
        self.label_26.setObjectName("label_26")
        
        self.label_27 = QtWidgets.QLabel(self.tab_11)
        self.label_27.setGeometry(QtCore.QRect(70, 110, 51, 20))
        self.label_27.setObjectName("label_27")
        
        self.label_28 = QtWidgets.QLabel(self.tab_11)
        self.label_28.setGeometry(QtCore.QRect(80, 150, 41, 20))
        self.label_28.setObjectName("label_28")
        
        self.lineEdit_25 = QtWidgets.QLineEdit(self.tab_11)
        self.lineEdit_25.setGeometry(QtCore.QRect(160, 30, 451, 25))
        self.lineEdit_25.setObjectName("lineEdit_25")
        
        self.lineEdit_26 = QtWidgets.QLineEdit(self.tab_11)
        self.lineEdit_26.setGeometry(QtCore.QRect(160, 70, 451, 25))
        self.lineEdit_26.setObjectName("lineEdit_26")
        
        self.lineEdit_27 = QtWidgets.QLineEdit(self.tab_11)
        self.lineEdit_27.setGeometry(QtCore.QRect(160, 110, 451, 25))
        self.lineEdit_27.setObjectName("lineEdit_27")
        
        self.lineEdit_28 = QtWidgets.QLineEdit(self.tab_11)
        self.lineEdit_28.setGeometry(QtCore.QRect(160, 150, 451, 25))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.lineEdit_28.setEchoMode(QtWidgets.QLineEdit.Password)
        
        self.toolButton_7 = QtWidgets.QToolButton(self.tab_11)
        self.toolButton_7.setGeometry(QtCore.QRect(640, 30, 26, 24))
        self.toolButton_7.setObjectName("toolButton_7")
        
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_7.setGeometry(QtCore.QRect(330, 190, 89, 25))
        self.pushButton_7.setObjectName("pushButton_7")
        
        self.textEdit_7 = QtWidgets.QTextEdit(self.tab_11)
        self.textEdit_7.setGeometry(QtCore.QRect(30, 230, 691, 231))
        self.textEdit_7.setObjectName("textEdit_7")
        
        self.tabWidget_3.addTab(self.tab_11, "")
        
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        
        self.lineEdit_29 = QtWidgets.QLineEdit(self.tab_12)
        self.lineEdit_29.setGeometry(QtCore.QRect(160, 30, 451, 25))
        self.lineEdit_29.setObjectName("lineEdit_29")
        
        self.textEdit_8 = QtWidgets.QTextEdit(self.tab_12)
        self.textEdit_8.setGeometry(QtCore.QRect(30, 230, 691, 231))
        self.textEdit_8.setObjectName("textEdit_8")
        
        self.label_29 = QtWidgets.QLabel(self.tab_12)
        self.label_29.setGeometry(QtCore.QRect(50, 70, 81, 20))
        self.label_29.setObjectName("label_29")
        
        self.label_30 = QtWidgets.QLabel(self.tab_12)
        self.label_30.setGeometry(QtCore.QRect(70, 110, 51, 20))
        self.label_30.setObjectName("label_30")
        
        self.lineEdit_30 = QtWidgets.QLineEdit(self.tab_12)
        self.lineEdit_30.setGeometry(QtCore.QRect(160, 70, 451, 25))
        self.lineEdit_30.setObjectName("lineEdit_30")
        
        self.toolButton_8 = QtWidgets.QToolButton(self.tab_12)
        self.toolButton_8.setGeometry(QtCore.QRect(640, 30, 26, 24))
        self.toolButton_8.setObjectName("toolButton_8")
        
        self.lineEdit_31 = QtWidgets.QLineEdit(self.tab_12)
        self.lineEdit_31.setGeometry(QtCore.QRect(160, 150, 451, 25))
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.lineEdit_31.setEchoMode(QtWidgets.QLineEdit.Password)

        
        self.lineEdit_32 = QtWidgets.QLineEdit(self.tab_12)
        self.lineEdit_32.setGeometry(QtCore.QRect(160, 110, 451, 25))
        self.lineEdit_32.setObjectName("lineEdit_32")
        
        self.label_31 = QtWidgets.QLabel(self.tab_12)
        self.label_31.setGeometry(QtCore.QRect(60, 30, 67, 17))
        self.label_31.setObjectName("label_31")
        
        self.label_32 = QtWidgets.QLabel(self.tab_12)
        self.label_32.setGeometry(QtCore.QRect(80, 150, 41, 20))
        self.label_32.setObjectName("label_32")
        
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_12)
        self.pushButton_8.setGeometry(QtCore.QRect(330, 190, 89, 25))
        self.pushButton_8.setObjectName("pushButton_8")
        
        self.tabWidget_3.addTab(self.tab_12, "")
        
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        
        self.lineEdit_33 = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_33.setGeometry(QtCore.QRect(160, 30, 451, 25))
        self.lineEdit_33.setObjectName("lineEdit_33")
        
        self.textEdit_9 = QtWidgets.QTextEdit(self.tab_13)
        self.textEdit_9.setGeometry(QtCore.QRect(30, 230, 691, 231))
        self.textEdit_9.setObjectName("textEdit_9")
        
        self.label_33 = QtWidgets.QLabel(self.tab_13)
        self.label_33.setGeometry(QtCore.QRect(50, 70, 81, 20))
        self.label_33.setObjectName("label_33")
        
        self.label_34 = QtWidgets.QLabel(self.tab_13)
        self.label_34.setGeometry(QtCore.QRect(70, 110, 51, 20))
        self.label_34.setObjectName("label_34")
        
        self.lineEdit_34 = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_34.setGeometry(QtCore.QRect(160, 70, 451, 25))
        self.lineEdit_34.setObjectName("lineEdit_34")
        
        self.toolButton_9 = QtWidgets.QToolButton(self.tab_13)
        self.toolButton_9.setGeometry(QtCore.QRect(640, 30, 26, 24))
        self.toolButton_9.setObjectName("toolButton_9")
        
        self.lineEdit_35 = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_35.setGeometry(QtCore.QRect(160, 150, 451, 25))
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.lineEdit_35.setEchoMode(QtWidgets.QLineEdit.Password)
        
        self.lineEdit_36 = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_36.setGeometry(QtCore.QRect(160, 110, 451, 25))
        self.lineEdit_36.setObjectName("lineEdit_36")
        
        self.label_35 = QtWidgets.QLabel(self.tab_13)
        self.label_35.setGeometry(QtCore.QRect(60, 30, 67, 17))
        self.label_35.setObjectName("label_35")
        
        self.label_36 = QtWidgets.QLabel(self.tab_13)
        self.label_36.setGeometry(QtCore.QRect(80, 150, 41, 20))
        self.label_36.setObjectName("label_36")
        
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_13)
        self.pushButton_9.setGeometry(QtCore.QRect(330, 190, 89, 25))
        self.pushButton_9.setObjectName("pushButton_9")
        
        self.tabWidget_3.addTab(self.tab_13, "")
        
        self.tabWidget.addTab(self.tab_2, "")
        
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget_4.setGeometry(QtCore.QRect(20, 10, 751, 511))
        self.tabWidget_4.setObjectName("tabWidget_4")
        
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        
        self.label_37 = QtWidgets.QLabel(self.tab_14)
        self.label_37.setGeometry(QtCore.QRect(60, 30, 67, 17))
        self.label_37.setObjectName("label_37")
        
        self.label_38 = QtWidgets.QLabel(self.tab_14)
        self.label_38.setGeometry(QtCore.QRect(50, 70, 81, 20))
        self.label_38.setObjectName("label_38")
        
        self.label_39 = QtWidgets.QLabel(self.tab_14)
        self.label_39.setGeometry(QtCore.QRect(70, 110, 51, 20))
        self.label_39.setObjectName("label_39")
        
        self.label_40 = QtWidgets.QLabel(self.tab_14)
        self.label_40.setGeometry(QtCore.QRect(80, 150, 41, 20))
        self.label_40.setObjectName("label_40")
        
        self.lineEdit_37 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_37.setGeometry(QtCore.QRect(160, 30, 451, 25))
        self.lineEdit_37.setObjectName("lineEdit_37")
        
        self.lineEdit_38 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_38.setGeometry(QtCore.QRect(160, 70, 451, 25))
        self.lineEdit_38.setObjectName("lineEdit_38")
        
        self.lineEdit_39 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_39.setGeometry(QtCore.QRect(160, 110, 451, 25))
        self.lineEdit_39.setObjectName("lineEdit_39")
        
        self.lineEdit_40 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_40.setGeometry(QtCore.QRect(160, 150, 451, 25))
        self.lineEdit_40.setObjectName("lineEdit_40")
        
        self.toolButton_10 = QtWidgets.QToolButton(self.tab_14)
        self.toolButton_10.setGeometry(QtCore.QRect(640, 30, 26, 24))
        self.toolButton_10.setObjectName("toolButton_10")
        
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_10.setGeometry(QtCore.QRect(330, 190, 89, 25))
        self.pushButton_10.setObjectName("pushButton_10")
        
        self.textEdit_10 = QtWidgets.QTextEdit(self.tab_14)
        self.textEdit_10.setGeometry(QtCore.QRect(30, 230, 691, 231))
        self.textEdit_10.setObjectName("textEdit_10")
        
        self.tabWidget_4.addTab(self.tab_14, "")
        
        self.tab_15 = QtWidgets.QWidget()
        
        self.tab_15.setObjectName("tab_15")
        
        self.lineEdit_41 = QtWidgets.QLineEdit(self.tab_15)
        self.lineEdit_41.setGeometry(QtCore.QRect(160, 30, 451, 25))
        self.lineEdit_41.setObjectName("lineEdit_41")
        
        self.textEdit_11 = QtWidgets.QTextEdit(self.tab_15)
        self.textEdit_11.setGeometry(QtCore.QRect(30, 230, 691, 231))
        self.textEdit_11.setObjectName("textEdit_11")
        
        self.label_41 = QtWidgets.QLabel(self.tab_15)
        self.label_41.setGeometry(QtCore.QRect(50, 70, 81, 20))
        self.label_41.setObjectName("label_41")
        
        self.label_42 = QtWidgets.QLabel(self.tab_15)
        self.label_42.setGeometry(QtCore.QRect(70, 110, 51, 20))
        self.label_42.setObjectName("label_42")
        
        self.lineEdit_42 = QtWidgets.QLineEdit(self.tab_15)
        self.lineEdit_42.setGeometry(QtCore.QRect(160, 70, 451, 25))
        self.lineEdit_42.setObjectName("lineEdit_42")
        
        self.toolButton_11 = QtWidgets.QToolButton(self.tab_15)
        self.toolButton_11.setGeometry(QtCore.QRect(640, 30, 26, 24))
        self.toolButton_11.setObjectName("toolButton_11")
        
        self.lineEdit_43 = QtWidgets.QLineEdit(self.tab_15)
        self.lineEdit_43.setGeometry(QtCore.QRect(160, 150, 451, 25))
        self.lineEdit_43.setObjectName("lineEdit_43")
        
        self.lineEdit_44 = QtWidgets.QLineEdit(self.tab_15)
        self.lineEdit_44.setGeometry(QtCore.QRect(160, 110, 451, 25))
        self.lineEdit_44.setObjectName("lineEdit_44")
        
        self.label_43 = QtWidgets.QLabel(self.tab_15)
        self.label_43.setGeometry(QtCore.QRect(60, 30, 67, 17))
        self.label_43.setObjectName("label_43")
        
        self.label_44 = QtWidgets.QLabel(self.tab_15)
        self.label_44.setGeometry(QtCore.QRect(80, 150, 41, 20))
        self.label_44.setObjectName("label_44")
        
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_15)
        self.pushButton_11.setGeometry(QtCore.QRect(330, 190, 89, 25))
        self.pushButton_11.setObjectName("pushButton_11")
        
        self.tabWidget_4.addTab(self.tab_15, "")
        
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        
        self.lineEdit_45 = QtWidgets.QLineEdit(self.tab_16)
        self.lineEdit_45.setGeometry(QtCore.QRect(160, 30, 451, 25))
        self.lineEdit_45.setObjectName("lineEdit_45")
        
        self.textEdit_12 = QtWidgets.QTextEdit(self.tab_16)
        self.textEdit_12.setGeometry(QtCore.QRect(30, 230, 691, 231))
        self.textEdit_12.setObjectName("textEdit_12")
        
        self.label_45 = QtWidgets.QLabel(self.tab_16)
        self.label_45.setGeometry(QtCore.QRect(50, 70, 81, 20))
        self.label_45.setObjectName("label_45")
        
        self.label_46 = QtWidgets.QLabel(self.tab_16)
        self.label_46.setGeometry(QtCore.QRect(70, 110, 51, 20))
        self.label_46.setObjectName("label_46")
        
        self.lineEdit_46 = QtWidgets.QLineEdit(self.tab_16)
        self.lineEdit_46.setGeometry(QtCore.QRect(160, 70, 451, 25))
        self.lineEdit_46.setObjectName("lineEdit_46")
        
        self.toolButton_12 = QtWidgets.QToolButton(self.tab_16)
        self.toolButton_12.setGeometry(QtCore.QRect(640, 30, 26, 24))
        self.toolButton_12.setObjectName("toolButton_12")
        
        self.lineEdit_47 = QtWidgets.QLineEdit(self.tab_16)
        self.lineEdit_47.setGeometry(QtCore.QRect(160, 150, 451, 25))
        self.lineEdit_47.setObjectName("lineEdit_47")
        
        self.lineEdit_48 = QtWidgets.QLineEdit(self.tab_16)
        self.lineEdit_48.setGeometry(QtCore.QRect(160, 110, 451, 25))
        self.lineEdit_48.setObjectName("lineEdit_48")
        
        self.label_47 = QtWidgets.QLabel(self.tab_16)
        self.label_47.setGeometry(QtCore.QRect(60, 30, 67, 17))
        self.label_47.setObjectName("label_47")
        
        self.label_48 = QtWidgets.QLabel(self.tab_16)
        self.label_48.setGeometry(QtCore.QRect(80, 150, 41, 20))
        self.label_48.setObjectName("label_48")
        
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_16)
        self.pushButton_12.setGeometry(QtCore.QRect(330, 190, 89, 25))
        self.pushButton_12.setObjectName("pushButton_12")
        
        self.tabWidget_4.addTab(self.tab_16, "")
        
        self.tabWidget.addTab(self.tab_3, "")
        
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        
        self.tabWidget_5 = QtWidgets.QTabWidget(self.tab_4)
        self.tabWidget_5.setGeometry(QtCore.QRect(20, 10, 751, 511))
        self.tabWidget_5.setObjectName("tabWidget_5")
        
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        
        self.label_49 = QtWidgets.QLabel(self.tab_17)
        self.label_49.setGeometry(QtCore.QRect(60, 30, 67, 17))
        self.label_49.setObjectName("label_49")
        
        self.label_50 = QtWidgets.QLabel(self.tab_17)
        self.label_50.setGeometry(QtCore.QRect(50, 70, 81, 20))
        self.label_50.setObjectName("label_50")
        
        self.label_51 = QtWidgets.QLabel(self.tab_17)
        self.label_51.setGeometry(QtCore.QRect(70, 110, 51, 20))
        self.label_51.setObjectName("label_51")
        
        self.label_52 = QtWidgets.QLabel(self.tab_17)
        self.label_52.setGeometry(QtCore.QRect(80, 150, 41, 20))
        self.label_52.setObjectName("label_52")
        
        self.lineEdit_49 = QtWidgets.QLineEdit(self.tab_17)
        self.lineEdit_49.setGeometry(QtCore.QRect(160, 30, 451, 25))
        self.lineEdit_49.setObjectName("lineEdit_49")
        
        self.lineEdit_50 = QtWidgets.QLineEdit(self.tab_17)
        self.lineEdit_50.setGeometry(QtCore.QRect(160, 70, 451, 25))
        self.lineEdit_50.setObjectName("lineEdit_50")
        
        self.lineEdit_51 = QtWidgets.QLineEdit(self.tab_17)
        self.lineEdit_51.setGeometry(QtCore.QRect(160, 110, 451, 25))
        self.lineEdit_51.setObjectName("lineEdit_51")
        
        self.lineEdit_52 = QtWidgets.QLineEdit(self.tab_17)
        self.lineEdit_52.setGeometry(QtCore.QRect(160, 150, 451, 25))
        self.lineEdit_52.setObjectName("lineEdit_52")
        
        self.toolButton_13 = QtWidgets.QToolButton(self.tab_17)
        self.toolButton_13.setGeometry(QtCore.QRect(640, 30, 26, 24))
        self.toolButton_13.setObjectName("toolButton_13")
        
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_17)
        self.pushButton_13.setGeometry(QtCore.QRect(330, 190, 89, 25))
        self.pushButton_13.setObjectName("pushButton_13")
        
        self.textEdit_13 = QtWidgets.QTextEdit(self.tab_17)
        self.textEdit_13.setGeometry(QtCore.QRect(30, 230, 691, 231))
        self.textEdit_13.setObjectName("textEdit_13")
        
        self.tabWidget_5.addTab(self.tab_17, "")
        
        self.tab_18 = QtWidgets.QWidget()
        self.tab_18.setObjectName("tab_18")
        
        self.lineEdit_53 = QtWidgets.QLineEdit(self.tab_18)
        self.lineEdit_53.setGeometry(QtCore.QRect(160, 30, 451, 25))
        self.lineEdit_53.setObjectName("lineEdit_53")
        
        self.textEdit_14 = QtWidgets.QTextEdit(self.tab_18)
        self.textEdit_14.setGeometry(QtCore.QRect(30, 230, 691, 231))
        self.textEdit_14.setObjectName("textEdit_14")
        
        self.label_53 = QtWidgets.QLabel(self.tab_18)
        self.label_53.setGeometry(QtCore.QRect(50, 70, 81, 20))
        self.label_53.setObjectName("label_53")
        
        self.label_54 = QtWidgets.QLabel(self.tab_18)
        self.label_54.setGeometry(QtCore.QRect(70, 110, 51, 20))
        self.label_54.setObjectName("label_54")
        
        self.lineEdit_54 = QtWidgets.QLineEdit(self.tab_18)
        self.lineEdit_54.setGeometry(QtCore.QRect(160, 70, 451, 25))
        self.lineEdit_54.setObjectName("lineEdit_54")
        
        self.toolButton_14 = QtWidgets.QToolButton(self.tab_18)
        self.toolButton_14.setGeometry(QtCore.QRect(640, 30, 26, 24))
        self.toolButton_14.setObjectName("toolButton_14")
        
        self.lineEdit_55 = QtWidgets.QLineEdit(self.tab_18)
        self.lineEdit_55.setGeometry(QtCore.QRect(160, 150, 451, 25))
        self.lineEdit_55.setObjectName("lineEdit_55")
        
        self.lineEdit_56 = QtWidgets.QLineEdit(self.tab_18)
        self.lineEdit_56.setGeometry(QtCore.QRect(160, 110, 451, 25))
        self.lineEdit_56.setObjectName("lineEdit_56")
        
        self.label_55 = QtWidgets.QLabel(self.tab_18)
        self.label_55.setGeometry(QtCore.QRect(60, 30, 67, 17))
        self.label_55.setObjectName("label_55")
        
        self.label_56 = QtWidgets.QLabel(self.tab_18)
        self.label_56.setGeometry(QtCore.QRect(80, 150, 41, 20))
        self.label_56.setObjectName("label_56")
        
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_18)
        self.pushButton_14.setGeometry(QtCore.QRect(330, 190, 89, 25))
        self.pushButton_14.setObjectName("pushButton_14")
        
        self.tabWidget_5.addTab(self.tab_18, "")
        
        self.tab_19 = QtWidgets.QWidget()
        self.tab_19.setObjectName("tab_19")
        
        self.lineEdit_57 = QtWidgets.QLineEdit(self.tab_19)
        self.lineEdit_57.setGeometry(QtCore.QRect(160, 30, 451, 25))
        self.lineEdit_57.setObjectName("lineEdit_57")
        
        self.textEdit_15 = QtWidgets.QTextEdit(self.tab_19)
        self.textEdit_15.setGeometry(QtCore.QRect(30, 230, 691, 231))
        self.textEdit_15.setObjectName("textEdit_15")
        
        self.label_57 = QtWidgets.QLabel(self.tab_19)
        self.label_57.setGeometry(QtCore.QRect(50, 70, 81, 20))
        self.label_57.setObjectName("label_57")
        
        self.label_58 = QtWidgets.QLabel(self.tab_19)
        self.label_58.setGeometry(QtCore.QRect(70, 110, 51, 20))
        self.label_58.setObjectName("label_58")
        
        self.lineEdit_58 = QtWidgets.QLineEdit(self.tab_19)
        self.lineEdit_58.setGeometry(QtCore.QRect(160, 70, 451, 25))
        self.lineEdit_58.setObjectName("lineEdit_58")
        
        self.toolButton_15 = QtWidgets.QToolButton(self.tab_19)
        self.toolButton_15.setGeometry(QtCore.QRect(640, 30, 26, 24))
        self.toolButton_15.setObjectName("toolButton_15")
        
        self.lineEdit_59 = QtWidgets.QLineEdit(self.tab_19)
        self.lineEdit_59.setGeometry(QtCore.QRect(160, 150, 451, 25))
        self.lineEdit_59.setObjectName("lineEdit_59")
        
        self.lineEdit_60 = QtWidgets.QLineEdit(self.tab_19)
        self.lineEdit_60.setGeometry(QtCore.QRect(160, 110, 451, 25))
        self.lineEdit_60.setObjectName("lineEdit_60")
        
        self.label_59 = QtWidgets.QLabel(self.tab_19)
        self.label_59.setGeometry(QtCore.QRect(60, 30, 67, 17))
        self.label_59.setObjectName("label_59")
        
        self.label_60 = QtWidgets.QLabel(self.tab_19)
        self.label_60.setGeometry(QtCore.QRect(80, 150, 41, 20))
        self.label_60.setObjectName("label_60")
        
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_19)
        self.pushButton_15.setGeometry(QtCore.QRect(330, 190, 89, 25))
        self.pushButton_15.setObjectName("pushButton_15")
        
        self.tabWidget_5.addTab(self.tab_19, "")
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_5.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)
# ----------------------------------- lmq -------------------------------------
        self.pushButton_7.clicked.connect(self.run_lmq_exp1)
        self.pushButton_8.clicked.connect(self.run_lmq_exp2)
        self.pushButton_9.clicked.connect(self.run_lmq_exp3)
        self.exp2_text = ""
# --------------------------------------- -------------------------------------

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "配置文件"))
        self.label_2.setText(_translate("Form", "控制节点IP"))
        self.label_3.setText(_translate("Form", "用户名"))
        self.label_4.setText(_translate("Form", "密码"))
        self.toolButton.setText(_translate("Form", "..."))
        self.pushButton.setText(_translate("Form", "运行"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("Form", "成果1"))
        self.label_5.setText(_translate("Form", "控制节点IP"))
        self.label_6.setText(_translate("Form", "用户名"))
        self.toolButton_2.setText(_translate("Form", "..."))
        self.label_7.setText(_translate("Form", "配置文件"))
        self.label_8.setText(_translate("Form", "密码"))
        self.pushButton_2.setText(_translate("Form", "运行"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("Form", "成果2"))
        self.label_9.setText(_translate("Form", "控制节点IP"))
        self.label_10.setText(_translate("Form", "用户名"))
        self.toolButton_3.setText(_translate("Form", "..."))
        self.label_11.setText(_translate("Form", "配置文件"))
        self.label_12.setText(_translate("Form", "密码"))
        self.pushButton_3.setText(_translate("Form", "运行"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("Form", "成果3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "传统科学计算"))
        self.label_25.setText(_translate("Form", "配置文件"))
        self.label_26.setText(_translate("Form", "控制节点IP"))
        self.label_27.setText(_translate("Form", "用户名"))
        self.label_28.setText(_translate("Form", "密码"))
        self.toolButton_7.setText(_translate("Form", "..."))
        self.pushButton_7.setText(_translate("Form", "运行"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_11), _translate("Form", "成果1"))
        self.label_29.setText(_translate("Form", "控制节点IP"))
        self.label_30.setText(_translate("Form", "用户名"))
        self.toolButton_8.setText(_translate("Form", "..."))
        self.label_31.setText(_translate("Form", "配置文件"))
        self.label_32.setText(_translate("Form", "密码"))
        self.pushButton_8.setText(_translate("Form", "运行"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_12), _translate("Form", "成果2"))
        self.label_33.setText(_translate("Form", "控制节点IP"))
        self.label_34.setText(_translate("Form", "用户名"))
        self.toolButton_9.setText(_translate("Form", "..."))
        self.label_35.setText(_translate("Form", "配置文件"))
        self.label_36.setText(_translate("Form", "密码"))
        self.pushButton_9.setText(_translate("Form", "运行"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_13), _translate("Form", "成果3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "大数据计算"))
        self.label_37.setText(_translate("Form", "配置文件"))
        self.label_38.setText(_translate("Form", "控制节点IP"))
        self.label_39.setText(_translate("Form", "用户名"))
        self.label_40.setText(_translate("Form", "密码"))
        self.toolButton_10.setText(_translate("Form", "..."))
        self.pushButton_10.setText(_translate("Form", "运行"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_14), _translate("Form", "成果1"))
        self.label_41.setText(_translate("Form", "控制节点IP"))
        self.label_42.setText(_translate("Form", "用户名"))
        self.toolButton_11.setText(_translate("Form", "..."))
        self.label_43.setText(_translate("Form", "配置文件"))
        self.label_44.setText(_translate("Form", "密码"))
        self.pushButton_11.setText(_translate("Form", "运行"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_15), _translate("Form", "成果2"))
        self.label_45.setText(_translate("Form", "控制节点IP"))
        self.label_46.setText(_translate("Form", "用户名"))
        self.toolButton_12.setText(_translate("Form", "..."))
        self.label_47.setText(_translate("Form", "配置文件"))
        self.label_48.setText(_translate("Form", "密码"))
        self.pushButton_12.setText(_translate("Form", "运行"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_16), _translate("Form", "成果3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "传统机器学习"))
        self.label_49.setText(_translate("Form", "配置文件"))
        self.label_50.setText(_translate("Form", "控制节点IP"))
        self.label_51.setText(_translate("Form", "用户名"))
        self.label_52.setText(_translate("Form", "密码"))
        self.toolButton_13.setText(_translate("Form", "..."))
        self.pushButton_13.setText(_translate("Form", "运行"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_17), _translate("Form", "成果1"))
        self.label_53.setText(_translate("Form", "控制节点IP"))
        self.label_54.setText(_translate("Form", "用户名"))
        self.toolButton_14.setText(_translate("Form", "..."))
        self.label_55.setText(_translate("Form", "配置文件"))
        self.label_56.setText(_translate("Form", "密码"))
        self.pushButton_14.setText(_translate("Form", "运行"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_18), _translate("Form", "成果2"))
        self.label_57.setText(_translate("Form", "控制节点IP"))
        self.label_58.setText(_translate("Form", "用户名"))
        self.toolButton_15.setText(_translate("Form", "..."))
        self.label_59.setText(_translate("Form", "配置文件"))
        self.label_60.setText(_translate("Form", "密码"))
        self.pushButton_15.setText(_translate("Form", "运行"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_19), _translate("Form", "成果3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "深度学习"))

# ---------------------------------- global -----------------------------------
    def selectSingleFile(self, lineEdit):
        file_path, _ = QFileDialog.getOpenFileName(self.Form, "选择文件", "", "All Files (*)")
        lineEdit.setText(file_path)
        

    def scp(self, master_ip, master_user, master_passwd, file):
        if master_user == "root":
            scp_cmd = "sshpass -p " + master_passwd + " scp " + file + " " + master_user + "@" + master_ip + ":/root/AsymCDC/clipper-asymcc/run/config/"
        else:
            scp_cmd = "sshpass -p " + master_passwd + " scp " + file + " " + master_user + "@" + master_ip + ":/home/" + master_user + "/wl/AsymCDC/clipper-asymcc/run/config/"
    
    def scp_lmq(self, master_ip, master_user, master_passwd, file, dst):
        if master_user == "root":
            scp_cmd = "sshpass -p " + master_passwd + " scp " + file + " " + master_user + "@" + master_ip + ":" + dst
        else:
            scp_cmd = "sshpass -p " + master_passwd + " scp " + file + " " + master_user + "@" + master_ip + ":" + dst
    
        # print(scp_cmd)
        return subprocess.getstatusoutput(scp_cmd)

    def exec(self, master_ip, master_user, master_passwd, cmd):
        ssh_cmd = "sshpass -p " + master_passwd + " ssh -p 22 -l" + master_user + " -o StrictHostKeyChecking=no " + master_ip
        return subprocess.getstatusoutput(ssh_cmd + cmd)
    
    def exec_lmq(self, master_ip, master_user, master_passwd, cmd):
        exec_cmd = f"sshpass -p {master_passwd} ssh {master_user}@{master_ip} \"{cmd}\""
        return subprocess.getstatusoutput(exec_cmd)

    def display_result(self, output, textEdit):
        textEdit.append(output)
        QApplication.processEvents()
    
    def cleanup_thread(self, worker):
        if worker:
            worker.wait()  # Ensure the thread has finished before continuing

    def add_escape(self, value):
        reserved_chars = r'''?&|!{}[]()^~*:\\"'+- '''
        replace = ['\\' + l for l in reserved_chars]
        trans = str.maketrans(dict(zip(reserved_chars, replace)))
        return value.translate(trans)
    
# -----------------------------------------------------------------------------

# ----------------------------------- xrq -------------------------------------
    def run_xrq_exp1(self):
        pass
    
    def run_xrq_exp2(self):
        pass
    
    def run_xrq_exp3(self):
        pass
# -----------------------------------------------------------------------------

# ----------------------------------- lmq -------------------------------------
    def run_lmq_exp1(self):
        root = "/root/MergeCDC"
        filename = self.lineEdit_25.text()
        master_ip = self.lineEdit_26.text()
        username = self.lineEdit_27.text()
        passwd = self.lineEdit_28.text()
        # filename = "/home/lmq/new_GUI/config/lmq/exp2.json"
        # master_ip = "8.152.160.205"
        # username = "root"
        # passwd = "hycB509!"
        with open(filename) as file:
            conf = json.load(file)
            distribution = conf["file_distribution"]
            combination = conf["node_combination"]
        
        # copy config file to master node
        self.scp_lmq(master_ip, username, passwd, filename, f"{root}/config/")
        self.scp_lmq(master_ip, username, passwd, distribution, f"{root}/Distribution/")
        self.scp_lmq(master_ip, username, passwd, combination, f"{root}/Distribution/")
        self.textEdit_7.append("[INFO] copy config file to master node done")
        QApplication.processEvents()
        print("[INFO] copy config file to master node done")
        # clear old bandwidth config
        ret = self.exec_lmq(master_ip, username, passwd, f"bash {root}/script/clear.sh")
        self.textEdit_7.append("[INFO] clear old bandwidth config done")
        QApplication.processEvents()
        print("[INFO] clear old bandwidth config done")
        # modify bandwidth config
        ret = self.exec_lmq(master_ip, username, passwd, f"bash {root}/script/update.sh")
        self.textEdit_7.append("[INFO] modify bandwidth config done")
        QApplication.processEvents()
        print("[INFO] modify bandwidth config done")

        # run TeraSort and CodedTeraSort
        self.textEdit_7.append("[INFO] run TeraSort and CodedTeraSort start")
        QApplication.processEvents()
        print("[INFO] run TeraSort and CodedTeraSort start")

        # worker = Worker(master_ip, username, passwd, f"bash {root}/script/run_1_terasort.sh")
        cmd = f"bash {root}/script/run_1_terasort.sh"
        exec_cmd = f"ssh {username}@{master_ip} \"{cmd}\""  
        worker = Worker("", exec_cmd)
        worker.start()
        worker.finished.connect(lambda: self.cleanup_thread(worker))
        worker.result_signal.connect(lambda output: self.display_result(output, self.textEdit_7))
    
    def run_lmq_exp2(self):
        # while True:
        #     Ui_Form.exp2_text = Ui_Form.exp2_text + "hello world\n"
        #     print(f"modify exp2_text: {Ui_Form.exp2_text}")
        #     Ui_Form.textEdit_8.setText(Ui_Form.exp2_text)
        #     QApplication.processEvents()
        #     time.sleep(1)
        # return
        root = "/root/exp2/MergeCDC"
        filename = self.lineEdit_29.text()
        master_ip = self.lineEdit_30.text()
        username = self.lineEdit_32.text()
        passwd = self.lineEdit_31.text()
        # filename = "/home/lmq/new_GUI/config/lmq/exp2.json"
        # master_ip = "8.152.160.205"
        # username = "root"
        # passwd = "hycB509!"
        with open(filename) as file:
            conf = json.load(file)
            distribution = conf["file_distribution"]
            combination = conf["node_combination"]
        # copy config file to master node
        self.scp_lmq(master_ip, username, passwd, filename, f"{root}/config/")
        self.scp_lmq(master_ip, username, passwd, distribution, f"{root}/Distribution/")
        self.scp_lmq(master_ip, username, passwd, combination, f"{root}/Distribution/")
        self.textEdit_8.append("[INFO] copy config file to master node done")
        QApplication.processEvents()
        print("[INFO] copy config file to master node done")
        # clear old bandwidth config
        ret = self.exec_lmq(master_ip, username, passwd, f"bash {root}/script/clear.sh")
        self.textEdit_8.append("[INFO] clear old bandwidth config done")
        QApplication.processEvents()
        print("[INFO] clear old bandwidth config done")
        # modify bandwidth config
        ret = self.exec_lmq(master_ip, username, passwd, f"bash {root}/script/update.sh")
        self.textEdit_8.append("[INFO] modify bandwidth config done")
        QApplication.processEvents()
        print("[INFO] modify bandwidth config done")

        # update bandwidth ratio
        ret = self.exec_lmq(master_ip, username, passwd, f"python3 {root}/script/update_bandwidth.py")
        print(ret)
        self.textEdit_8.append("[INFO] modify bandwidth ratio done")
        QApplication.processEvents()
        print("[INFO] modify bandwidth ratio done")
        
        # run TeraSort and CodedTeraSort
        self.textEdit_8.append("[INFO] run TeraSort and CodedTeraSort start")
        QApplication.processEvents()
        print("[INFO] run TeraSort and CodedTeraSort start")

        # worker = Worker(master_ip, username, passwd, f"bash {root}/script/run_1_terasort.sh")
        # worker = Worker(master_ip, username, passwd, f"bash {root}/script/run_8_terasort.sh")
        # worker = Worker(master_ip, username, passwd, f"bash {root}/script/run_8_codedterasort.sh")
        cmd = f"bash {root}/script/run_8_terasort.sh; bash {root}/script/run_8_codedterasort.sh"
        exec_cmd = f"ssh {username}@{master_ip} \"{cmd}\""  
        worker = Worker("", exec_cmd)
        # worker = Worker(master_ip, username, passwd, f"bash {root}/script/helloworld.sh")
        worker.start()
        worker.finished.connect(lambda: self.cleanup_thread(worker))
        worker.result_signal.connect(lambda output: self.display_result(output, self.textEdit_8))

        # ret = exec(master_ip, username, passwd, f"bash {root}/script/run_8.sh")
        # Ui_Form.textEdit_8.append("[INFO] run TeraSort and CodedTeraSort done")
        # QApplication.processEvents()
        # print("[INFO] run TeraSort and CodedTeraSort done")
        # Ui_Form.textEdit_8.append("[INFO] result:")
        # Ui_Form.textEdit_8.append(ret[1])
        # QApplication.processEvents()

    def run_lmq_exp3(self):
        root = "/root/exp3/MergeCDC"
        # filename = "/home/lmq/new_GUI/config/lmq/exp2.json"
        # master_ip = "8.152.160.205"
        # username = "root"
        # passwd = "hycB509!"
        filename = self.lineEdit_33.text()
        master_ip = self.lineEdit_34.text()
        username = self.lineEdit_36.text()
        passwd = self.lineEdit_35.text()
        with open(filename) as file:
            conf = json.load(file)
            distribution = conf["file_distribution"]
            combination = conf["node_combination"]
        
        # copy config file to master node
        self.scp_lmq(master_ip, username, passwd, filename, f"{root}/config/")
        self.scp_lmq(master_ip, username, passwd, distribution, f"{root}/Distribution/")
        self.scp_lmq(master_ip, username, passwd, combination, f"{root}/Distribution/")
        self.textEdit_9.append("[INFO] copy config file to master node done")
        QApplication.processEvents()
        print("[INFO] copy config file to master node done")
        # clear old bandwidth config
        ret = self.exec_lmq(master_ip, username, passwd, f"bash {root}/script/clear.sh")
        self.textEdit_9.append("[INFO] clear old bandwidth config done")
        QApplication.processEvents()
        print("[INFO] clear old bandwidth config done")
        # modify bandwidth config
        ret = self.exec_lmq(master_ip, username, passwd, f"bash {root}/script/update.sh")
        self.textEdit_9.append("[INFO] modify bandwidth config done")
        QApplication.processEvents()
        print("[INFO] modify bandwidth config done")

        # run TeraSort and CodedTeraSort
        self.textEdit_9.append("[INFO] run TeraSort and CodedTeraSort start")
        QApplication.processEvents()
        print("[INFO] run TeraSort and CodedTeraSort start")

        # worker = Worker(master_ip, username, passwd, f"bash {root}/script/run_1_terasort.sh")
        cmd = f"bash {root}/script/run_1_terasort.sh"
        exec_cmd = f"ssh {username}@{master_ip} \"{cmd}\""  
        worker = Worker("", exec_cmd)
        worker.start()
        worker.finished.connect(lambda: self.cleanup_thread(worker))
        worker.result_signal.connect(lambda output: self.display_result(output, self.textEdit_9))
# -----------------------------------------------------------------------------

# ----------------------------------- wdh -------------------------------------
    def run_wdh_exp1(self):
        pass
    
    def run_wdh_exp2(self):
        pass
    
    def run_wdh_exp3(self):
        pass
# -----------------------------------------------------------------------------

# ----------------------------------- wl -------------------------------------
    def run_wl_exp1(self):
        pass
    
    def run_wl_exp2(self):
        pass
    
    def run_wl_exp3(self):
        pass
# -----------------------------------------------------------------------------